<?php
/**
 * ExpenseEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Expense
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Expense API
 *
 * ConnectWise Expense API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Expense;

/**
 * ExpenseEntryTest Class Doc Comment
 *
 * @category    Class */
// * @description ExpenseEntry
/**
 * @package     Spinen\ConnectWise\Clients\Expense
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExpenseEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ExpenseEntry"
     */
    public function testExpenseEntry()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {

    }

    /**
     * Test attribute "charge_to_id"
     */
    public function testPropertyChargeToId()
    {

    }

    /**
     * Test attribute "charge_to_type"
     */
    public function testPropertyChargeToType()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "member"
     */
    public function testPropertyMember()
    {

    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {

    }

    /**
     * Test attribute "classification"
     */
    public function testPropertyClassification()
    {

    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {

    }

    /**
     * Test attribute "billable_option"
     */
    public function testPropertyBillableOption()
    {

    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "business_unit_id"
     */
    public function testPropertyBusinessUnitId()
    {

    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {

    }

    /**
     * Test attribute "agreement"
     */
    public function testPropertyAgreement()
    {

    }

    /**
     * Test attribute "invoice_amount"
     */
    public function testPropertyInvoiceAmount()
    {

    }

    /**
     * Test attribute "taxes"
     */
    public function testPropertyTaxes()
    {

    }

    /**
     * Test attribute "invoice"
     */
    public function testPropertyInvoice()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
