<?php
/**
 * ExpenseTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Expense
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Expense API
 *
 * ConnectWise Expense API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\Expense;

/**
 * ExpenseTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description ExpenseType
/**
 * @package     Spinen\ConnectWise\Clients\Expense
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExpenseTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ExpenseType"
     */
    public function testExpenseType()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "amount_caption"
     */
    public function testPropertyAmountCaption()
    {

    }

    /**
     * Test attribute "reimbursement_rate"
     */
    public function testPropertyReimbursementRate()
    {

    }

    /**
     * Test attribute "bill_expenses"
     */
    public function testPropertyBillExpenses()
    {

    }

    /**
     * Test attribute "invoice_markup_option"
     */
    public function testPropertyInvoiceMarkupOption()
    {

    }

    /**
     * Test attribute "invoice_markup_amount"
     */
    public function testPropertyInvoiceMarkupAmount()
    {

    }

    /**
     * Test attribute "advanced_amount_flag"
     */
    public function testPropertyAdvancedAmountFlag()
    {

    }

    /**
     * Test attribute "mileage_flag"
     */
    public function testPropertyMileageFlag()
    {

    }

    /**
     * Test attribute "quantity_flag"
     */
    public function testPropertyQuantityFlag()
    {

    }

    /**
     * Test attribute "inactive_flag"
     */
    public function testPropertyInactiveFlag()
    {

    }

    /**
     * Test attribute "max_amount"
     */
    public function testPropertyMaxAmount()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
