<?php
/**
 * ExpenseTypesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Expense
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Expense API
 *
 * ConnectWise Expense API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Expense;

use \Spinen\ConnectWise\Clients\Expense\Configuration;
use \Spinen\ConnectWise\Clients\Expense\ApiClient;
use \Spinen\ConnectWise\Clients\Expense\ApiException;
use \Spinen\ConnectWise\Clients\Expense\ObjectSerializer;

/**
 * ExpenseTypesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Expense
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ExpenseTypesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for expenseTypesCountGet
     *
     * .
     *
     */
    public function testExpenseTypesCountGet()
    {

    }

    /**
     * Test case for expenseTypesGet
     *
     * .
     *
     */
    public function testExpenseTypesGet()
    {

    }

    /**
     * Test case for expenseTypesIdDelete
     *
     * .
     *
     */
    public function testExpenseTypesIdDelete()
    {

    }

    /**
     * Test case for expenseTypesIdGet
     *
     * .
     *
     */
    public function testExpenseTypesIdGet()
    {

    }

    /**
     * Test case for expenseTypesIdPatch
     *
     * .
     *
     */
    public function testExpenseTypesIdPatch()
    {

    }

    /**
     * Test case for expenseTypesIdPut
     *
     * .
     *
     */
    public function testExpenseTypesIdPut()
    {

    }

    /**
     * Test case for expenseTypesPost
     *
     * .
     *
     */
    public function testExpenseTypesPost()
    {

    }

}
