<?php
/**
 * ExpenseEntriesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Expense
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Expense API
 *
 * ConnectWise Expense API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\Expense;

use \Spinen\ConnectWise\Clients\Expense\Configuration;
use \Spinen\ConnectWise\Clients\Expense\ApiClient;
use \Spinen\ConnectWise\Clients\Expense\ApiException;
use \Spinen\ConnectWise\Clients\Expense\ObjectSerializer;

/**
 * ExpenseEntriesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\Expense
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ExpenseEntriesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for expenseEntriesCountGet
     *
     * .
     *
     */
    public function testExpenseEntriesCountGet()
    {

    }

    /**
     * Test case for expenseEntriesGet
     *
     * .
     *
     */
    public function testExpenseEntriesGet()
    {

    }

    /**
     * Test case for expenseEntriesIdDelete
     *
     * .
     *
     */
    public function testExpenseEntriesIdDelete()
    {

    }

    /**
     * Test case for expenseEntriesIdGet
     *
     * .
     *
     */
    public function testExpenseEntriesIdGet()
    {

    }

    /**
     * Test case for expenseEntriesIdPatch
     *
     * .
     *
     */
    public function testExpenseEntriesIdPatch()
    {

    }

    /**
     * Test case for expenseEntriesIdPut
     *
     * .
     *
     */
    public function testExpenseEntriesIdPut()
    {

    }

    /**
     * Test case for expenseEntriesPost
     *
     * .
     *
     */
    public function testExpenseEntriesPost()
    {

    }

}
